name: Deploying Mini-Market App to Surge

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Build Mini-Market App
        run: yarn build
      - name: Install Surge
        run: npm install --global surge
      - name: Run surge
        run: surge ./dist ${{env.SURGE_URL}} --token ${{ secrets.SURGE_TOKEN }}
